# Generated by Django 5.1.1 on 2025-01-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_useraccount_alter_friends_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='description',
            field=models.CharField(default='A cool hobby', max_length=1024),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Hobbies',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='api.hobby'),
        ),
    ]
