# Generated by Django 5.1.1 on 2025-01-11 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hobby_description_alter_hobby_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='api.profile'),
        ),
    ]
